"""empty message

Revision ID: 4882e4fffb46
Revises: c52e7f99962b
Create Date: 2024-02-05 13:47:33.890394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4882e4fffb46'
down_revision = 'c52e7f99962b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('about_me', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('member_since', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('member_since')
        batch_op.drop_column('about_me')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
